"""WZ encryption primitives.

Mirrors ``MapleLib/MapleCryptoLib`` and ``MapleLib/WzLib/Util/WzMutableKey.cs``.
A WZ key stream is generated by repeatedly AES-256-ECB encrypting the
4-byte region IV (repeated to fill a 16-byte block); strings and listWz
canvas data are XOR'd against that stream.
"""

from __future__ import annotations

from typing import Dict

from Crypto.Cipher import AES


# 4-byte IVs per region (from WzAESConstant.cs).
WZ_IV: Dict[str, bytes] = {
    "GMS": bytes([0x4D, 0x23, 0xC7, 0x2B]),
    "EMS": bytes([0xB9, 0x7D, 0x63, 0xE9]),
    "BMS": bytes([0x00, 0x00, 0x00, 0x00]),  # also CLASSIC / modern 64-bit
}

# Constant XOR'd into encrypted offsets.
WZ_OFFSET_CONSTANT = 0x581C3F6D

# 128-byte master key from MapleCryptoConstants.cs (verified against the
# actual bytes embedded in MapleLib.dll). The earlier copy of this constant
# diverged from the canonical value starting at byte 32, which made
# AES-derived keystreams for non-zero IVs (GMS, EMS) silently incorrect —
# BMS still worked because its zero IV bypasses AES entirely.
MAPLESTORY_USERKEY_DEFAULT = bytes([
    0x13, 0x00, 0x00, 0x00, 0x52, 0x00, 0x00, 0x00, 0x2A, 0x00, 0x00, 0x00, 0x5B, 0x00, 0x00, 0x00,
    0x08, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
    0x06, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x43, 0x00, 0x00, 0x00, 0x0F, 0x00, 0x00, 0x00,
    0xB4, 0x00, 0x00, 0x00, 0x4B, 0x00, 0x00, 0x00, 0x35, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x1B, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x5F, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x0F, 0x00, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x0C, 0x00, 0x00, 0x00, 0x1B, 0x00, 0x00, 0x00,
    0x33, 0x00, 0x00, 0x00, 0x55, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x52, 0x00, 0x00, 0x00, 0xDE, 0x00, 0x00, 0x00, 0xC7, 0x00, 0x00, 0x00, 0x1E, 0x00, 0x00, 0x00,
])


def _trim_user_key(user_key: bytes) -> bytes:
    """Reduce the 128-byte UserKey to a 32-byte AES-256 key.

    Matches ``MapleCryptoConstants.GetTrimmedUserKey``: 8 source bytes at
    every 16th offset are scattered into ``key[i/4]``, leaving the other
    24 bytes zero (which is correct — the C# code does the same).
    """
    key = bytearray(32)
    for i in range(0, 128, 16):
        key[i // 4] = user_key[i]
    return bytes(key)


_AES_KEY = _trim_user_key(MAPLESTORY_USERKEY_DEFAULT)


class WzKey:
    """On-demand keystream derived from a region IV.

    For ``BMS``/``CLASSIC`` (all-zero IV) the keystream is also all zeros so
    XOR is a no-op — matching ``WzMutableKey.EnsureKeySize``.
    """

    __slots__ = ("_iv", "_data")

    def __init__(self, iv: bytes):
        if len(iv) != 4:
            raise ValueError("IV must be 4 bytes")
        self._iv = iv
        self._data = bytearray()

    @classmethod
    def for_region(cls, region: str) -> "WzKey":
        return cls(WZ_IV[region])

    def ensure(self, size: int) -> None:
        if size <= len(self._data):
            return
        # Round up to the next 16-byte block.
        target = (size + 15) & ~15
        if int.from_bytes(self._iv, "little") == 0:
            self._data = bytearray(target)
            return
        cipher = AES.new(_AES_KEY, AES.MODE_ECB)
        block = bytearray(16)
        out = bytearray(self._data)
        # Continue from where we left off.
        i = len(out)
        while i < target:
            if i == 0:
                for j in range(16):
                    block[j] = self._iv[j % 4]
            else:
                block[:] = out[i - 16:i]
            out += cipher.encrypt(bytes(block))
            i += 16
        self._data = out

    def __getitem__(self, index: int) -> int:
        if index >= len(self._data):
            self.ensure(index + 1)
        return self._data[index]

    def slice(self, length: int) -> bytes:
        self.ensure(length)
        return bytes(self._data[:length])


class StaticWzKey(WzKey):
    """A ``WzKey`` whose keystream bytes are supplied verbatim and never
    extended via AES.

    Useful when the file uses a non-standard cipher and the caller has
    recovered (some prefix of) the raw keystream from known plaintext —
    for example via :func:`derive_keystream_from_property`. ``ensure(N)``
    zero-extends past the supplied length: short strings decode
    correctly, longer ones get garbage bytes past the boundary which
    the caller can spot in the output.
    """

    __slots__ = ()

    def __init__(self, data: bytes):
        super().__init__(b"\x00\x00\x00\x00")
        self._data = bytearray(data)

    def ensure(self, size: int) -> None:
        if size > len(self._data):
            self._data = self._data + bytearray(size - len(self._data))


def derive_keystream_from_property(data: bytes) -> bytes:
    """Recover the first 8 keystream bytes from an .img header.

    Every standard WZ image starts with ``0x73`` (Property tag) followed by
    a sign byte ``0xF8`` (= -8, ASCII length) and 8 cipher-encoded bytes
    that decrypt to ``"Property"``. With known plaintext we can solve for
    keystream[i] = raw[i] XOR (0xAA + i) XOR "Property"[i].

    Raises :class:`ValueError` if the buffer doesn't look like a Property
    image header.
    """
    if len(data) < 10 or data[0] != 0x73 or data[1] != 0xF8:
        raise ValueError(
            "not a Property .img header (expected byte 0=0x73, byte 1=0xF8)"
        )
    return bytes(data[2 + i] ^ (0xAA + i) ^ b"Property"[i] for i in range(8))


def detect_region_from_img(data: bytes):
    """Return the region name whose key decodes the .img's type_name to
    ``"Property"``, or ``None`` if no built-in region matches.

    Used by callers that have raw .img bytes and want to pick a cipher
    automatically. Cheap: only reads the first ~10 bytes per candidate.
    """
    import io
    from .reader import WzBinaryReader
    for region in WZ_IV.keys():
        reader = WzBinaryReader(io.BytesIO(data), WzKey.for_region(region))
        try:
            tag = reader.read_byte()
            type_name = reader.read_string()
        except Exception:
            continue
        if tag == 0x73 and type_name == "Property":
            return region
    return None


def compute_version_hash(version: int) -> int:
    """Compute the version hash from a MapleStory patch number."""
    h = 0
    for ch in str(version):
        h = (h * 32 + ord(ch) + 1) & 0xFFFFFFFF
    return h


def derive_version_check(version_hash: int) -> int:
    """Derive the encrypted version-check byte stored in the WZ header."""
    a = (version_hash >> 24) & 0xFF
    b = (version_hash >> 16) & 0xFF
    c = (version_hash >> 8) & 0xFF
    d = version_hash & 0xFF
    return (~(a ^ b ^ c ^ d)) & 0xFF
